---
AWSTemplateFormatVersion: '2010-09-09'
Description: provision aws lambda function resource infrastructure stack
Parameters:
  env:
    Description: Environment name to provision resources
    Type: String
    AllowedValues: ["dev", "prod"]
    Default: dev
  zipfileKey: 
    Description: Lambda function zip file key in S3 bucket, appending checksum to zipfile base name  
    Type: String

Resources:
  
  IamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        env: !Ref env
      TemplateURL: http://lambda-function-stack-templates-home.s3.amazonaws.com/nested/iam.yml
      TimeoutInMinutes: '5'  

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        env: !Ref env
        roleARN: !GetAtt IamStack.Outputs.RoleARN
        zipfileKey: !Ref zipfileKey
      TemplateURL: http://lambda-function-stack-templates-home.s3.amazonaws.com/nested/lambda.yml
      TimeoutInMinutes: '5'

Outputs:
  RoleName:
    Value: !GetAtt IamStack.Outputs.RoleName
    Description: RoleName of Lambda execution role
  RoleARN:
    Value: !GetAtt IamStack.Outputs.RoleARN
    Description: RoleARN of Lambda execution role  
  LambdaFunctionName:
    Value: !GetAtt LambdaStack.Outputs.LambdaFunctionName
    Description: Name of Lambda function