---
AWSTemplateFormatVersion: '2010-09-09'

Description: 'AWS CloudFormation Template for creating S3 bucket. This S3 bucket will be used to store cloudformation templates for this lambda function stack.'

Metadata: 
  License: Apache-2.0

Parameters:
  env:
    Description: Environment name to provision resources
    Type: String
    AllowedValues: ["dev", "prod"]
    Default: dev

Mappings: 
  BucketName: 
    dev: 
      Name: "simple-sinatra-stack-templates-home-dev"
    prod: 
      Name: "simple-sinatra-stack-templates-home-prod"

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !FindInMap
        - BucketName
        - !Ref env
        - Name
      Tags:
        - Key: "Project"
          Value: "Provision-AWS-via-Lambda-Function"
        - Key: "Createdby"
          Value: "fen9li"
        - Key: "ChargeTo"
          Value: !Ref env
    DeletionPolicy: Delete

Outputs:
  BucketName:
    Value: !Ref 'Bucket'
    Description: Name of S3 bucket to home simple sinatra stack templates
