name: upload aws lambda function

on: 
  push:
    branches:
    - develop
    - feature

jobs:
  build:
    name: build dev environment 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    - name: Sync 'lambda-function-stack-dev' templates to aws s3 bucket 'lambda-function-stack-templates-home'
      run: |
        aws s3 sync templates/lambda s3://lambda-function-stack-templates-home --delete
    - name: zip lambda function python code and sync it to 'lambda-function-zipfile-home-dev' bucket
      run: |
        zip provision-aws-resource-function.zip provision-aws-resource-function.py
        mkdir zipfile
        mv provision-aws-resource-function.zip zipfile/
        aws s3 sync zipfile s3://lambda-function-zipfile-home-dev --delete
    - name: Create stack if not exists 
      env:
        stackName: lambda-function-stack-dev
        stackTemplateUrl: "http://lambda-function-stack-templates-home.s3.amazonaws.com/lambda-function-stack.yml"
        env: dev
      run: |
        ./.github/bin/stack-exists.sh      
